services:
  discord-bot:
    build: .
    image: ghcr.io/solaris-games/solaris-discord-bot:1.0
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - SOLARIS_API_BASE_URL=${SOLARIS_API_BASE_URL}
      - CHAT_IDS=${CHAT_IDS}
    network_mode: "host"